[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#4B7BFF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
